### ISSUE TITLE
Can you publish a new version with updated luamin?

### ISSUE THREAD

**Issue by phoriah** [informagico/vscode-lua-minify#21]
Hello again.

**Comment by phoriah** [comment]
@informagico

**Comment by informagico** [comment]
Hello 😄 I suppose you are using the `lua-format` flavour.
I see that Herrtt pushed a new version yesterday, let me work on this

**Comment by informagico** [comment]
Ok I updated dependencies, let me take some tests and then I'll release the v.1.4.0 to marketplace
