### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Rubylium** [informagico/vscode-lua-minify#4]
Would it be possible to have a function to minify an entire project folder? So global variables in other files can be seen and renamed.
Sela would be amazing. Thank you!

**Comment by informagico** [comment]
@Rubylium let me figure this out, I think I can work on this by the weekend 😎

**Comment by informagico** [comment]
@Rubylium I know it's been a long time but I actually managed to work on this feature.
I will close this and mark as duplicated of #11
