### ISSUE TITLE
Compatibility request

### ISSUE THREAD

**Issue by phoriah** [informagico/vscode-lua-minify#8]
I'm using this for minifying LUAU (A fork of LUA made by Roblox) and it has compound operators, which aren't supported in native LUA
therefore it results in unexpected identifier error
Example:
`i += 1`
is same as
`i = i + 1`
List of all compound operators https://developer.roblox.com/en-us/articles/#Comp

Could you add support for these please

**Comment by informagico** [comment]
Hello! Thanks for the request 😄 
Under the hood I am using the great [https://github.com/mathiasbynens/luamin](https://github.com/mathiasbynens/luamin) from @mathiasbynens and therefore this is an issue to be opened there.

In any case I'll take a look and see what I can do, but no promises 🤞🏼

**Comment by phoriah** [comment]
Should I open the issue right now or wait for your response?

**Comment by informagico** [comment]
Yes go ahead, I'll take a look on that tomorrow.

**Comment by informagico** [comment]
@phoriah please try to update to v0.7.0 and set this into `settings.json` (see CHANGELOG for more details):
```json
"vscode-lua-minify": {
  "flavour": "lua-format"
}
```
This should allow you to minify Luau files/code.
Let me know if you find anything wrong 😄

**Comment by phoriah** [comment]
Hello, thanks for your work. The error has disappeared, however, it no longer shortens whole code into one line anymore

**Comment by informagico** [comment]
Can you please provide some example code that is not working?

**Comment by phoriah** [comment]
Here you go:
```
if THIS and not THAT == true then
	return print("WWW")
end

if THOSE then
	if not pcall(function()
		THOSE().LOAD = true
	end) then
		_G.LOAD = true
		print("FAILED")
	end
else
    _G.LOAD = true
    print("FAILED")
end
if not ({ [10101] = true, [1010110101] = true, [101011010110101] = true })[that] then
	return
end

local GlobalSettings = settings()
GlobalSettings:GetService("DebugSettings").TickCountPreciseOverride = 0
--* <------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
HMM, HI = "SOME", "AWE"
local W1, W2, W3, W4, W44, W444, W55, W5, W66 =
	true, { 1, 0, 0 }, false, 5, 25555, { 1, 0, 0 }, 0, 0.5
local cf = {
	["AMAZING"] = {
		["AMAZING"] = true,
	},
	["huh"] = {
		["huh"] = 10,
		["AwesomeAwesomeAwesomeAwesome"] = 1,
		["AwesomeAwesome"] = 2,
		["Awesome"] = {
			["WWWWWW"] = true,
			["WWW"] = true,
		},
	},
	["WWWWWWWWW"] = 7,
	["WWWC"] = 1,
	["WWWWWW"] = {},
	["WWW"] = {
		["CoolCool"] = "NONE",
		["CoolCoolCool"] = "NONE",
		["Cool"] = "NONE",
		["CoolCoolCoolCoolCoolCool"] = "F",
	},
	["CoolCoolCoolCoolCoolCoolCoolCoolCool"] = true,
	["CoolCoolCoolCoolCoolCoolCoolCool"] = 0.25,
	["CoolCoolCoolCoolCoolCoolCool"] = 0.8,
	["CoolCoolCoolCoolCoolCool"] = {
		["CoolCool"] = true,
		["Cool"] = true,
	},
	["CoolCoolCoolCool"] = {
		["CoolCool"] = false,
		["Cool"] = false,
	},
	["CoolCoolCool"] = {
		["CoolCoolCool"] = {
			["CoolCool"] = true,
			["Cool"] = true,
			["CoolCoolCool"] = true,
		},
		["CoolCool"] = {
			["Cool"] = {
				["Cool"] = { 0, 0.5, 1 },
			},
		},
		["Cool"] = {
			["CoolCool"] = "Cool",
			["CoolCoolCool"] = "Cool",
			["Cool"] = "Cool",
		},
	},
	["CoolCool"] = {},
	["Cool"] = 0.8,
}
```

**Comment by informagico** [comment]
I took a look on this and I need more time to investigate, lua-format supports LUAU but apparently somehow it does not like the nested table you're declaring.

I will peek code from [https://github.com/Herrtt/luamin.js](https://github.com/Herrtt/luamin.js) and see if something catches my attention, otherwise I'll open an issue.

Thank you and sorry for the extension to not work as expected 😞

**Comment by phoriah** [comment]
> I took a look on this and I need more time to investigate, lua-format supports LUAU but apparently somehow it does not like the nested table you're declaring.
> 
> I will peek code from https://github.com/Herrtt/luamin.js and see if something catches my attention, otherwise I'll open an issue.
> 
> Thank you and sorry for the extension to not work as expected 😞

Could you replace the current luamin with https://github.com/Herrtt/luamin.js/ under the hood? That should do the job.
Thanks, P.

**Comment by phoriah** [comment]
@informagico

**Comment by informagico** [comment]
Hello @phoriah 😄  glad to have you here!
That package is already included in the currently released extension, I bumped that package from v1.3.3 to v.1.3.4 on [update-lua-format-134](/informagico/vscode-lua-minify/tree/update-lua-format-134) branch.

Here you can find a preview of the extension, please refer to [README.md](https://github.com/informagico/vscode-lua-minify/blob/update-lua-format-134/README.md#settings) for instruction on how to configure it.
Let me know!

[vscode-lua-minify-0.7.1.vsix.zip](https://github.com/informagico/vscode-lua-minify/files/9672441/vscode-lua-minify-0.7.1.vsix.zip)

**Comment by phoriah** [comment]
> Hello @phoriah 😄 glad to have you here! That package is already included in the currently released extension, I bumped that package from v1.3.3 to v.1.3.4 on [update-lua-format-134](/informagico/vscode-lua-minify/tree/update-lua-format-134) branch.
> 
> Here you can find a preview of the extension, please refer to [README.md](https://github.com/informagico/vscode-lua-minify/blob/update-lua-format-134/README.md#settings) for instruction on how to configure it. Let me know!
> 
> [vscode-lua-minify-0.7.1.vsix.zip](https://github.com/informagico/vscode-lua-minify/files/9672441/vscode-lua-minify-0.7.1.vsix.zip)

Hello @informagico , the owner of that repository has fixed the issue but npm package has not been updated. Could you please grab the code from their repository manually and bundle it with a new release of your extension? That should resolve this issue once and for all, I believe!
Thanks,
P.

**Comment by informagico** [comment]
Hello @phoriah 😁 I pushed a version 0.7.1 to the marketplace.
Please switch to the `pre-release` branch and let me know if it fixes your issue.

**Comment by phoriah** [comment]
> Hello @phoriah 😁 I pushed a version 0.7.1 to the marketplace. Please switch to the `pre-release` branch and let me know if it fixes your issue.

Yes it did, just tested. Thank you very much for your help!
